version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Mudar123
      MYSQL_DATABASE: taskdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "5552:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql